// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Message struct {
	ID          int64              `json:"id"`
	RecipientID int64              `json:"recipient_id"`
	Content     string             `json:"content"`
	IsRead      bool               `json:"is_read"`
	IsBlocked   bool               `json:"is_blocked"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Reply struct {
	ID        int64              `json:"id"`
	MessageID int64              `json:"message_id"`
	AuthorID  interface{}        `json:"author_id"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           int64              `json:"id"`
	Username     string             `json:"username"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	IsActive     bool               `json:"is_active"`
	IsVerified   bool               `json:"is_verified"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
