// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
)

type Querier interface {
	CreateMessage(ctx context.Context, arg CreateMessageParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteMessage(ctx context.Context, id int64) error
	GetMessages(ctx context.Context, username string) ([]GetMessagesRow, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ReplyToMessage(ctx context.Context, arg ReplyToMessageParams) error
}

var _ Querier = (*Queries)(nil)
