// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package database

import (
	"context"
)

const deleteMessage = `-- name: DeleteMessage :exec
delete from messages
where id = $1
`

func (q *Queries) DeleteMessage(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteMessage, id)
	return err
}

const getMessages = `-- name: GetMessages :many
select id, recepient_id, content, is_read, is_blocked, created_at from messages
where recepient_id = $1
limit 10
`

func (q *Queries) GetMessages(ctx context.Context, recepientID int64) ([]Message, error) {
	rows, err := q.db.Query(ctx, getMessages, recepientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.RecepientID,
			&i.Content,
			&i.IsRead,
			&i.IsBlocked,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
select id, username, email, password_hash, is_active, is_verified, created_at from users
where id = $1 limit 1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.IsVerified,
		&i.CreatedAt,
	)
	return i, err
}
