// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
)

type Querier interface {
	DeleteMessage(ctx context.Context, id int64) error
	GetMessages(ctx context.Context, recepientID int64) ([]Message, error)
	GetUser(ctx context.Context, id int64) (User, error)
}

var _ Querier = (*Queries)(nil)
