// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :exec
insert into messages (recipient_id, content)
values ($1, $2)
`

type CreateMessageParams struct {
	RecipientID int64  `json:"recipient_id"`
	Content     string `json:"content"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) error {
	_, err := q.db.Exec(ctx, createMessage, arg.RecipientID, arg.Content)
	return err
}

const createUser = `-- name: CreateUser :exec
insert into users (username, email, password_hash)
values ($1, $2, $3)
`

type CreateUserParams struct {
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser, arg.Username, arg.Email, arg.PasswordHash)
	return err
}

const deleteMessage = `-- name: DeleteMessage :exec
delete from messages
where id = $1
`

func (q *Queries) DeleteMessage(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteMessage, id)
	return err
}

const getMessages = `-- name: GetMessages :many
select u.username, m.content from users u
left join messages m
on u.username = m.recipient_id
group by u.username
having username = $1
limit 10
`

type GetMessagesRow struct {
	Username string      `json:"username"`
	Content  pgtype.Text `json:"content"`
}

func (q *Queries) GetMessages(ctx context.Context, username string) ([]GetMessagesRow, error) {
	rows, err := q.db.Query(ctx, getMessages, username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMessagesRow
	for rows.Next() {
		var i GetMessagesRow
		if err := rows.Scan(&i.Username, &i.Content); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByUsername = `-- name: GetUserByUsername :one
select id, username, email, password_hash, is_active, is_verified, created_at from users
where username = $1 limit 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.IsVerified,
		&i.CreatedAt,
	)
	return i, err
}

const replyToMessage = `-- name: ReplyToMessage :exec
insert into replies (message_id, author_id, content)
values ($1, $2, $3)
`

type ReplyToMessageParams struct {
	MessageID int64       `json:"message_id"`
	AuthorID  interface{} `json:"author_id"`
	Content   string      `json:"content"`
}

func (q *Queries) ReplyToMessage(ctx context.Context, arg ReplyToMessageParams) error {
	_, err := q.db.Exec(ctx, replyToMessage, arg.MessageID, arg.AuthorID, arg.Content)
	return err
}
